### ISSUE TITLE
Build failed due to use of deprecated Android v1 embedding.

### ISSUE THREAD

**Issue by mrmoeed** [londonappbrewery/Clima-Flutter-Completed#34]
I know these tutorial files are old, but is it possible to run these files now?

**Comment by Gsuyash20** [comment]
Yes, just follow the steps on this website: https://flutter.dev/go/android-project-migration 
or you can create your own project and then copy paste everything 
or if you are on discord join the Appbrewery flutter server, there you can find it

**Comment by mrmoeed** [comment]
Thanks for replying back. :-)
