### ISSUE TITLE
A RenderFlex overflowed by 29 pixels on the bottom.

### ISSUE THREAD

**Issue by it-one-mm** [londonappbrewery/Clima-Flutter-Completed#8]
The relevant error-causing widget was: 
  Column file:///D:/FlutterApps/Clima-Flutter-master/lib/screens/location_screen.dart:60:18
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#d8db2 OVERFLOWING
...  parentData: offset=Offset(0.0, 24.0) (can use size)
...  constraints: BoxConstraints(w=411.4, h=377.1)
...  size: Size(411.4, 377.1)
...  direction: vertical
...  mainAxisAlignment: spaceBetween
...  mainAxisSize: max
...  crossAxisAlignment: stretch
...  verticalDirection: down
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by beinghasan** [comment]
Same error I'm also getting when I put a cursor in TextField.

W/IInputConnectionWrapper(14591): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(14591): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(14591): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(14591): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(14591): endBatchEdit on inactive InputConnection

The relevant error-causing widget was:
Column file:///D:/FlutterApps/Clima-Flutter-master/lib/screens/location_screen.dart:60:18
The overflowing RenderFlex has an orientation of Axis.vertical.
